<test-run id="2" duration="80.554574" testcasecount="2" total="2" passed="0" failed="2" inconclusive="0" skipped="0" result="Failed" start-time="2023-12-13T 06:08:06Z" end-time="2023-12-13T 06:09:27Z">
  <test-suite type="Assembly" name="framework.dll" fullname="C:\Frameworks\Playwright.NET\framework\bin\Debug\net7.0\framework.dll" total="2" passed="0" failed="2" inconclusive="0" skipped="0" result="Failed" start-time="2023-12-13T 06:08:06Z" end-time="2023-12-13T 06:09:27Z" duration="80.554574">
    <test-suite type="TestSuite" name="framework" fullname="framework" total="2" passed="0" failed="2" inconclusive="0" skipped="0" result="Failed" start-time="2023-12-13T 06:08:06Z" end-time="2023-12-13T 06:09:27Z" duration="80.554574">
      <test-suite type="TestSuite" name="TestCases" fullname="framework.TestCases" total="2" passed="0" failed="2" inconclusive="0" skipped="0" result="Failed" start-time="2023-12-13T 06:08:06Z" end-time="2023-12-13T 06:09:27Z" duration="80.554574">
        <test-suite type="TestFixture" name="DemoSessionTwo" fullname="framework.TestCases.DemoSessionTwo" classname="framework.TestCases.DemoSessionTwo" total="2" passed="0" failed="2" inconclusive="0" skipped="0" result="Failed" start-time="2023-12-13T 06:08:06Z" end-time="2023-12-13T 06:09:27Z" duration="80.554574">
          <test-case name="LoginWithInvalidCredentials" fullname="framework.TestCases.DemoSessionTwo.LoginWithInvalidCredentials" methodname="LoginWithInvalidCredentials" classname="DemoSessionTwo" result="Failed" start-time="2023-12-13T 06:08:06Z" end-time="2023-12-13T 06:08:49Z" duration="42.938312" asserts="0" seed="1524698459">
            <properties>
              <property name="REGRESSION" value="LOGIN" />
              <property name="Category" value="TES-53" />
            </properties>
            <output><![CDATA[NOFalse
Locator expected to be enabled 
Call log:
LocatorAssertions.ToBeEnabledAsync with timeout 10000ms
waiting for GetByRole(AriaRole.Button, new() { Name = "User account details" })
  Expected: True
  But was:  False


]]></output>
            <failure>
              <message>  Expected: True
  But was:  False
</message>
              <stack-trace>   at framework.TestCases.DemoSessionTwo.LoginWithInvalidCredentials() in C:\Frameworks\Playwright.NET\framework\TestCases\DemoSessionTwo.cs:line 90

1)    at framework.TestCases.DemoSessionTwo.LoginWithInvalidCredentials() in C:\Frameworks\Playwright.NET\framework\TestCases\DemoSessionTwo.cs:line 90

</stack-trace>
            </failure>
          </test-case>
          <test-case name="LoginWithValidCredentials" fullname="framework.TestCases.DemoSessionTwo.LoginWithValidCredentials" methodname="LoginWithValidCredentials" classname="DemoSessionTwo" result="Failed" start-time="2023-12-13T 06:08:49Z" end-time="2023-12-13T 06:09:27Z" duration="37.616262" asserts="0" seed="1448658770">
            <properties>
              <property name="REGRESSION" value="LOGIN" />
              <property name="Category" value="TES-52" />
            </properties>
            <output><![CDATA[NOFalse
Locator expected to be enabled 
Call log:
LocatorAssertions.ToBeEnabledAsync with timeout 10000ms
waiting for GetByRole(AriaRole.Button, new() { Name = "User account details" })
  Expected: True
  But was:  False


]]></output>
            <failure>
              <message>  Expected: True
  But was:  False
</message>
              <stack-trace>   at framework.TestCases.DemoSessionTwo.LoginWithValidCredentials() in C:\Frameworks\Playwright.NET\framework\TestCases\DemoSessionTwo.cs:line 46

1)    at framework.TestCases.DemoSessionTwo.LoginWithValidCredentials() in C:\Frameworks\Playwright.NET\framework\TestCases\DemoSessionTwo.cs:line 46

</stack-trace>
            </failure>
          </test-case>
        </test-suite>
      </test-suite>
    </test-suite>
    <errors />
  </test-suite>
</test-run>